teutonet/teutonet-helm-charts

- charts/base-cluster/values.yaml
This allows for a smooth transition from the initial `helm install` to a flux managed `base-cluster`
> feat(base-cluster): add teuto-net HelmRepository

- .github/workflows/label-release-pr.yaml
- .github/workflows/semver.yaml
also, there can only be one chart changed per commit, so we don't have
to run a matrix job
> fix(ci): use latest release specific to chart, properly label release PRs

- charts/base-cluster/templates/ingress/nginx.yaml
As this has no downside we enable brotli and gzip compression for the nginx.
> feat(base-cluster): enable brotli and gzip

- .github/workflows/label-release-pr.yaml
> feat(ci): Always remove label from closed PR, only add on merged PR, don't run semver on release

- charts/t8s-cluster/templates/workload-cluster/_helmRelease.yaml
- charts/t8s-cluster/templates/workload-cluster/ccm.yaml
- charts/t8s-cluster/templates/workload-cluster/cni.yaml
- charts/t8s-cluster/templates/workload-cluster/csi.yaml
depends on https://gitlab.teuto.net/4teuto/ops/k8s/t8s-engine-management-cluster/flux-deployment/-/merge_requests/84
> fix(t8s-cluster): remove serviceAccountName for HelmReleases

- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/values.yaml
add main version to values.yaml
each descheduler's minor version supports (d minor)-2 k8s minor versions, therefore we can use (k8s minor)+2 as the descheduler version
> feat(base-cluster/descheduler): update descheduler supported versions

- charts/t8s-cluster/templates/workload-cluster/_helmRelease.yaml
- charts/t8s-cluster/templates/workload-cluster/cni-cilium.yaml
in preparation of https://github.com/fluxcd/helm-controller/issues/643 we raise the reconcile times, as the reconciliation might now really do some work, finally!
> feat(t8s-cluster): drift detection

- charts/base-cluster/templates/ingress/nginx.yaml
This
- enables the proxy protocol for the HCLB
- removes private IPs from the ingress service
- This "fixes" the external-dns, without it it creates DNS records with internal IPs
> feat(base-cluster/ingress): support hetzner cloud loadbalancer

- .github/workflows/release-update-metadata.yaml
Should fix https://github.com/teutonet/teutonet-helm-charts/actions/runs/4817708418/jobs/8578769369?pr=320
> fix(ci): add missing prepare-values for release metadata

- charts/base-cluster/templates/ingress/nginx.yaml
the `ingressClassResource.default` only "configures" a mutatingwebhook that sets the `.spec.ingressClassName` on new ingresses, whereas the `watchIngressWithoutClass` makes nginx just watch ingresses without a defined IngressClass.
The first one only works if the IngressClass exists before the ingress does, while the second works with all ingresses, whenever they are created and leaves more flexibility to the user to swap the ingress without having to change all ingresses
Closes #375
> fix(base-cluster/ingress): change "kind" of default

- .github/renovate.json
This should fix https://app.renovatebot.com/dashboard#github/teutonet/teutonet-helm-charts/1080333285
> fix(renovate): use https:// URL for oci instead of oci://

- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
If during initial cluster creation problems occur, the controlPlane won't be fixed, as `1/2` => `50%` of nodes are unhealthy.
`33%` of a healthy controlPlane are `1`, so changing this value /essentially/ doesn't change anything except in the case of a new cluster.
The same goes for the machineDeployments, in the initial startup phase nothing gets fixed, as the percentage is always hit. And as machineDeployments aren't as critical as the controlPlane we can just recycle broken nodes whenever.
> feat(t8s-cluster/management-cluster): adjust machineHealthCheck

- charts/base-cluster/templates/backup/velero.yaml
To use aws provider an init-container is needed.
Staticly added.
> fix(base-cluster/kyverno): add aws provider

- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/kubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_kubeadmControlPlaneTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/patches/_kubelet.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/patches/_patches.tpl
The kubelet doesn't have that flag, it has to be configured via the config file.
While doing this I also switched from flags to config file for the other variables, as they are also deprecated.
---
feat(t8s-cluster/management-cluster): ease troubleshooting by printing the kubelet journal on error
> fix(t8s-cluster/management-cluster): fix kubelet configuration

- charts/t8s-cluster/templates/management-cluster/uninstall.yaml
The HelmReleases might be leftover if flux isn't fast enough to delete them or has errors during the uninstallation. Especially the latter happened quite a lot during testing.
> feat(t8s-cluster/management-cluster): cleanup for uninstallation

- charts/t8s-cluster/templates/management-cluster/clusterClass/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackMachineTemplates/_openstackMachineTemplateSpec.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
Changing the openStackMachineTemplates resulted in a rolling of the machines in the old version and then again in the new version.
As now the openStackMachineTemplates are not touched this doesn't happen anymore.
> fix(t8s-cluster/clusterClass): fix redundant rolling of machines

- charts/t8s-cluster/templates/management-cluster/cluster.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
This is in preparation for our internal teuto-portal -> k8s worker
> feat(t8s-cluster/management-cluster): add friendlyName field instead of cluster name

- charts/base-cluster/templates/ingress/nginx.yaml
In preparation of the migration of customer clusters this change is needed.
> feat(base-cluster/nginx): enable underscores in headers

- .github/renovate.json
- .github/scripts/validate-and-label-pullrequest.sh
this also allows us to better check the PR and also label it
This also makes PRs like https://github.com/teutonet/teutonet-helm-charts/pull/503 work, see failed check
> feat(ci/renovate): split PRs by project

- .github/renovate.json
See https://github.com/teutonet/teutonet-helm-charts/pull/507
I somehow thought renovate would join it with a `-`
> fix(ci/renovate): add missing `-`-suffix

- charts/t8s-cluster/templates/management-cluster/check-k8s-version.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
Currently the user can (accidentally) downgrade the k8s version, which is of course not supported
This job checks the new version against the running version and fails it is lower
> feat(t8s-cluster/management-cluster): validate new k8s version before upgrade

- .github/scripts/prepare-values.sh
The values.yaml is the base for all the other `ci/*-values.yaml`s, therefore changing them as well is not needed
> feat(ci/scripts): only add `_common.sh` to main `values.yaml`

- charts/base-cluster/templates/_images.tpl
- charts/base-cluster/values.yaml
this has been unneeded since https://github.com/teutonet/teutonet-helm-charts/pull/178
> chore(base-cluster): remove pause container image configuration

- .github/workflows/validate-and-label-pullrequest.yaml
As we don't have the required checks anymore, this will only ever be executed on the PR and therefore work without having to fall back to the default_branch
> fix(ci): use current PR's branch

- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/_kubeadmConfigTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_kubeadmControlPlaneTemplateSpec.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
As now we're not really proxying anymore, we're just mirroring.
This means that the nodes are allowed to pull directly from upstream if something is wrong with the mirror.
> feat(t8s-cluster)!: change `proxy` to `mirror`

- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
during our alpha/beta phase, we don't have enough GPU compute nodes, therefore we can't create a new node before deleting an old one
> feat(t8s-cluster/management-cluster): don't surge GPU nodes

- charts/base-cluster/templates/kyverno/kyverno.yaml
this basically doesn't change anything, as the
open-telemetry-collector-opentelemetry-collector service' internalTrafficPolicy is local anyway
> feat(base-cluster/tracing): simplify tracingConfig

- charts/t8s-cluster/templates/workload-cluster/cinder-csi-plugin.yaml
- charts/t8s-cluster/templates/workload-cluster/cloud-controller-manager.yaml
- charts/t8s-cluster/templates/workload-cluster/cni-cilium.yaml
- charts/t8s-cluster/templates/workload-cluster/gpu-operator.yaml
during cluster upgrades the rolling nodes can lead to `upgrade retries exhausted` because the daemonsets can't roll quick enough
> feat(t8s-cluster/workload-cluster): add a higher timeout for upgrading

- charts/base-cluster/ci/priorityclasses-values.yaml
- charts/base-cluster/templates/backup/velero.yaml
- charts/base-cluster/templates/cert-manager/cert-manager.yaml
- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/templates/dns/external-dns.yaml
- charts/base-cluster/templates/global/priorityClasses.yaml
- charts/base-cluster/templates/global/reflector.yaml
- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_alertmanager-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_kube-state-metrics-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_node-exporter-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus-stack-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus_config.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/templates/monitoring/metrics-server/metrics-server.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
nginx is of course required for ingress
descheduler is especially important in scenarios where the cluster is running low on resources, which may be only because of poor scheduling
> feat(base-cluster): add priorityClassName to critical applications

- charts/base-cluster/templates/kyverno/kyverno.yaml
Kyverno decided to add a key before the excluded namespaces..
> fix(base-cluster/kyverno): fix excluded namespaces

- charts/teuto-portal-k8s-worker/Chart.yaml
- charts/teuto-portal-k8s-worker/values.schema.json
- charts/teuto-portal-k8s-worker/values.yaml
It is necessary to make the rennvoate bot work
> ci(teuto-portal-k8s-worker): move imageRegistry to worker values

- charts/t8s-cluster/templates/workload-cluster/cinder-csi-plugin.yaml
Sometimes the compute-plane might not be available
> feat(t8s-cluster/cinder-csi-plugin): allow to run on control-plane

- charts/base-cluster/templates/cert-manager/rules/certificate-expiration.yaml
otherwise new certs practically always trigger this alert
This still triggers if they fail to get issues after 5 minutes
Closes #648
> fix(base-cluster/cert-manager): debounce certificate-expiration alert

- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/templates/backup/credentials.yaml
- charts/base-cluster/templates/backup/migrations/velero-4-to-5.yaml
- charts/base-cluster/templates/backup/validation.yaml
- charts/base-cluster/templates/backup/velero.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_grafana-config.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
> fix(base-cluster/backup)!: only enable velero if a backupstoragelocation is set

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_grafana-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/oauth-proxy-secret.yaml
- charts/base-cluster/values.yaml
Closes #751, see https://github.com/grafana/helm-charts/pull/2867 The update to kube-prometheus-stack is necessary, otherwise https://github.com/grafana/helm-charts/pull/2910 is not included
> fix(base-cluster/grafana): oidc secret handling

- charts/t8s-cluster/values.yaml
This is only compatible with the new t8s-engine operator
> feat(t8s-cluster)!: migrate to new image names

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/oauth-proxy.yaml
especially if no wildcard certificate is available
> fix(base-cluster/oauth-proxy): use correct secretName for certificate

- charts/t8s-cluster/templates/management-cluster/clusterClass/_helpers.tpl
> feat(t8s-cluster/management-cluster)!: migrate to new secret naming

- charts/t8s-cluster/ci/artifacthub-values.yaml
- charts/t8s-cluster/templates/management-cluster/cluster.yaml
- charts/t8s-cluster/values.schema.json
> feat(t8s-cluster/management-cluster)!: add environment parameter

- charts/base-cluster/templates/descheduler/descheduler.yaml
> feat(base-cluster/descheduler): run as deployment and enable prometheus

- charts/base-cluster/templates/monitoring/tracing/grafana-tempo.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
the new default, nano, was too small for the test cluster
> feat(base-cluster/tracing): add resources settings for ingester

- .github/scripts/create-values-diff.sh
- .github/scripts/extract-artifacthub-images.sh
- .github/scripts/templateHelmChart.sh
- .github/workflows/release-update-metadata.yaml
therefore the developer should just override the image via the artifacthub-values.yaml to `artifacthub-ignore`
This also forces the detected images to end the line, which conveniently throws out the `charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_openStackClusterTemplateSpec.yaml` ignored image
> fix(ci/artifacthub-images): the artifacthub-ignore comments get lost,

- .github/workflows/linter.yaml
oci repos can't be added this way and are working just fine without this
> fix(ci/linting): only parse https helm repos

- .github/workflows/create-release-prs.yaml
- .github/workflows/release-chart.yaml
now that google has moved the release please repository, the actions are also updated from the deprecated to the upstream repo.
https://github.com/google-github-actions/release-please-action?tab=readme-ov-file
> fix(ci): update release please path

- charts/base-cluster/values.schema.json
There were working-hours alerts at night, which should happen.
The reason seems to be that the label definition in our alertmanager is `WorkingHours` and not `Working-Hours`.
> fix(base-cluster): set correct label for workinghours

- .github/trusted_registries.yaml
Reverts teutonet/teutonet-helm-charts#994
This image doesn't exist, the correct way to have "fixed" this, would've been to adjust the registry replacement
> revert(ci): "fix(ci): add busybox as trusted image"

- charts/t8s-cluster/templates/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/repositories/cni-calico.yaml
- charts/t8s-cluster/templates/workload-cluster/cinder-csi-plugin.yaml
- charts/t8s-cluster/templates/workload-cluster/cloud-controller-manager.yaml
- charts/t8s-cluster/templates/workload-cluster/cni-calico.yaml
- charts/t8s-cluster/templates/workload-cluster/cni-cilium.yaml
- charts/t8s-cluster/templates/workload-cluster/pre-install/uninstall-cni.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
This should allow us to adopt the legacy clusters into our customer portal
> feat(t8s-cluster/workload-cluster): latch onto legacy cni when used

- charts/base-cluster/templates/monitoring/kdave/kdave.yaml
The kdave helm chart does not support image version 2.x.x.
So either we use 1.x.x (probably 1.0.3 as it's the default) or we disable kdave alltogether.
> fix(base-cluster/kdave): image 2.x.x is unsupported by the helm chart

- .github/workflows/scan-for-cves.yaml
One would imagine that the default would make more sense than being _outside the workfolder_
chore(ci/cve-scanning): update action
> fix(ci/cve-scanning): override sarif_file location

- .github/workflows/scan-for-cves.yaml
upload-sarif action is not smart enough to not throw an error...
> fix(ci/cve-scanning): skip uploading if no reports exist

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus-stack-config.yaml
- charts/base-cluster/templates/tetragon/tetragon.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
Ref.: https://github.com/teutonet/teutonet-helm-charts/issues/1046
> feat(base-cluster/tetragon): add tetragon

- .github/CODEOWNERS
I really don't see the point of reviews right now, as they only slow down development by _multiple days_ and yet more often than not mistakes get overlooked.
This will now be lead like Linux is.
> chore(ci): dictatorship ahoy!

- .github/scripts/enforce-trusted-registries.sh
- .github/scripts/extract-artifacthub-images.sh
- .github/scripts/sync-codeowners.sh
- .github/scripts/templateHelmChartRecursivelyToFolder.sh
- .github/workflows/update-artifacthub-images.yaml
inlining the `&&` or `||` is more performant checking for existance of files or directories is safer than string comparing
> chore(ci): improve scripts

- .github/scripts/generate-sarif-reports.sh
- .github/scripts/scan-for-licenses.sh
- .github/workflows/check-licenses.yaml
- .github/workflows/get-all-charts.yaml
- .github/workflows/scan-for-cves.yaml
We want to check the licenses used by our software and get an error if a critical license is used without us acknowledging it.
> feat(ci): check licenses

- .github/scripts/generate-sarif-reports.sh
otherwise the last run overrides the earlier, see <https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#uploading-more-than-one-sarif-file-for-a-commit>
> fix(ci/cve-scanning): up retries and use a unique category for each chart

- .github/workflows/update-artifacthub-images.yaml
- .github/workflows/update-codeowners.yaml
see <https://github.com/teutonet/teutonet-helm-charts/pull/1183> and <https://github.com/teutonet/teutonet-helm-charts/pull/1165>
> fix(ci): trigger workflows with automated PRs

- .github/release-please/config.json
This reverts commit 06064e02ff50ae1b1498f425850c9067d2cbbfbf.
Since release-please-action is not yet updated 🙄
See <https://github.com/googleapis/release-please-action/issues/428>
> chore(ci/release-please): Revert "feat(ci/release-please): use a nicer PR title (#1179)"

- charts/base-cluster/templates/rbac/_rbac.tpl
- charts/base-cluster/templates/rbac/roleBindings.yaml
- charts/base-cluster/templates/rbac/roles.yaml
The most often used rbac roles are exactly the default ones, this eases
that configuration
this is breaking because one might already use these names, but they are
now forbidden
> feat(base-cluster/rbac)!: allow to use the k8s default ClusterRoles

- charts/base-cluster/Chart.yaml
- charts/base-cluster/templates/descheduler/descheduler.yaml
chore(base-cluster/descheduler): up the minimum kubernetes version to 1.27.x
this should've already happened, but renovate force-pushed this over,
see <https://github.com/teutonet/teutonet-helm-charts/pull/1173#event-15001996224>
> chore(base-cluster/dependencies): update helm release descheduler to 0.31.x

- charts/t8s-cluster/values.schema.json
this is not needed, as the type is `string` anyways and set to an empty string by default
> fix(t8s-cluster): remove unnecessary require for openstackImageNamePrefix

- charts/t8s-cluster/templates/workload-cluster/_helmRelease.yaml
otherwise `{}` will be inserted, breaking everything
> fix(t8s-cluster): only `toYaml` if field exists

- .github/scripts/scan-for-licenses.sh
The teuto-k8s-worker is private, trivy is blocking pulls.
> fix(ci): add last missing license, exclude private or blocked images

- charts/base-cluster/templates/monitoring/kdave/kdave.yaml
otherwise this fails on an empty cluster
> fix(base-cluster/kdave): deploy wrapped ServiceMonitor

- charts/t8s-cluster/templates/management-cluster/repositories/cni-calico.yaml
see <https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#supported-versions>
> fix(t8s-cluster/cni): otherwise for >=1.30 there is no version

- .github/scripts/create-values-diff.sh
- .github/workflows/check-licenses.yaml
- .github/workflows/pr-comment-diff.yaml
Reverts teutonet/teutonet-helm-charts#1269
I thought the path `pr/..` was some filesystem trick to mimic the pr in the filesystem, but there simply not existing. 
I don't know how @cwrau thought this to work, so i revert it for now.
> feat(ci): revert: adjust scripts to run safely for external PRs

- .github/workflows/linter.yaml
Pipelines fail because the python version 3.7 is eol
> fix(ci): user newer, not eol, python version

- .github/workflows/check-licenses.yaml
- .github/workflows/label-pullrequest.yaml
- .github/workflows/pr-comment-diff.yaml
- .github/workflows/release-update-metadata.yaml
- .github/workflows/validate-pullrequest.yaml
- .github/workflows/wait-for-checks.yaml
<https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context:~:text=branch%2D1.-,github.ref_name,-string> should include the pr_number, but alas it does not...
> fix(ci): stupid github docs

- .github/workflows/update-artifacthub-images.yaml
the `-f "$chart/ci/artifacthub-values.yaml"` check is not actually
required, as we require `artifacthub-values.yaml`s for each chart
anyway
> fix(ci/artifacthub): use central `get-all-charts` and add missing `PR_NUMBER`

- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_openStackClusterTemplateSpec.yaml
I could've _sworn_ that the docs had these values in uppercase...
> fix(t8s-cluster): me be stupid I guess

- .github/workflows/wait-for-checks.yaml
since their names changed, this ignore didn't work correctly
> feat(ci): ignore these jobs

- .github/workflows/release-update-metadata.yaml
otherwise the run will be triggered again, push again and be triggerd a
third time.
> fix(ci): only push after the last commit

- charts/base-cluster/templates/NOTES.txt
otherwise the validation fails with `baseDomain needed`
> fix(base-cluster/monitoring): use correct condition for grafana ingress

- .github/scripts/generate-sarif-reports.sh
- .github/scripts/sarif-report-collect-results.jq
otherwise the results have some duplicated entries
The unique shouldn't hide any CVEs, as the whole object is used for uniqueness
> fix(ci): `unique` cve result to deduplicate

- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmControlPlaneTemplate/_kubeadmControlPlaneTemplateSpec.yaml
volume names cannot contain `.`
> fix(t8s-cluster/management-cluster): invalid volume names

- charts/base-cluster/templates/kyverno/kyverno.yaml
See the documentation
https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml#L713-L715
> feat(base-cluster/kyverno): enable policyExceptions for kyverno
