teutonet/teutonet-helm-charts

- .github/CODEOWNERS
- .github/renovate.json
- .github/scripts/sync-codeowners.sh
- .github/scripts/validate-pullrequest.sh
- .github/workflows/conventional-commits.yaml
- .github/workflows/linter.yaml
- .github/workflows/release.yaml
- .github/workflows/sync-codeowners-and-docs.yaml
- .github/workflows/validate-pullrequest.yaml
- .gitignore
- README.md
> feat: initial CI commit

- .github/workflows/release.yaml
chore(base-cluster): bump version
Should fix #12
> fix(ci): don't overwrite README on release

- .github/auto_assign.yml
- .github/workflows/auto-assign-pr.yaml
- .github/workflows/conventional-commits.yaml
- .github/workflows/linter.yaml
- .github/workflows/release.yaml
- .github/workflows/sync-codeowners-and-docs.yaml
- .github/workflows/validate-pullrequest.yaml
> feat(ci): add auto-assign action

- .github/json-schema-to-md.yaml
- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/NOTES.txt
- charts/base-cluster/templates/_images.tpl
- charts/base-cluster/templates/flux/_create-ssh-key-secret-job.yaml
- charts/base-cluster/templates/flux/_create-ssh-key-secret-rbac.yaml
- charts/base-cluster/templates/flux/flux.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
Generate SSH keys if they don't already exist
> feat(base-cluster): auto-generate ssh keys when using SSH git URLs

- charts/base-cluster/.helmignore
- charts/base-cluster/templates/NOTES.txt
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/generate-etcd-secret-job.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/grafana-secret.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
- add hook-weight to hook
- adjust .helmignore
- correctly fetch the grafana admin password in the NOTES.txt
- formatting
- allow ssh urls for flux
- remove unused properties
- use stable labels for secret
- add secret checksum to grafana pod to enable password changing
> chore(base-cluster): various little changes

- .github/workflows/auto-assign-pr.yaml
- .github/workflows/label-release-pr.yaml
- .github/workflows/release.yaml
- .github/workflows/semver.yaml
change workflow name
adjust release PR name and template
> fix(ci): only label release PRs

- .github/scripts/extract-artifacthub-images.sh
- .github/workflows/extract-artifacthub-images.yaml
- .github/workflows/release.yaml
- .github/workflows/sync-codeowners-and-docs.yaml
ArtifactHUB needs an annotation to correctly check the included images; https://artifacthub.io/docs/topics/annotations/helm/
This workflow+script aims to provide this
> feat(ci): generate artifacthub image annotation

- charts/base-cluster/Chart.lock
- charts/base-cluster/ci/artifacthub-values.yaml
> feat(base-cluster): add ci values for artifacthub

- .github/workflows/semver.yaml
The CLI works with comma separated values
> fix(ci): needs to be json for some reason 🤷

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/sync-etcd-secret-daemonset.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/sync-etcd-secret-rbac.yaml
> feat(base-cluster): replace etcd secret job hook with a daemonset

- charts/base-cluster/templates/flux/flux.yaml
- charts/base-cluster/values.schema.json
> feat(base-cluster): add ref selection

- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/ingress/validation.tpl
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
> feat(base-cluster): add option to use a specific IP

- charts/base-cluster/templates/global/_secret-sync-cronjob.yaml
> fix(base-cluster): add status selector for namespaces

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/sync-etcd-secret-daemonset.yaml
> fix(base-cluster): correctly configure prometheus to scrape etcd via

- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/ci/artifacthub-values.yaml
- charts/base-cluster/templates/_hosts.tpl
- charts/base-cluster/templates/kyverno/kyverno.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/values.yaml
- add installation notice about bootstrapping
- adjust hosts templating
- adjust artifacthub-values ci configuration to include the gpg image
- up loki timeout
- adjust values schema reference
> feat(base-cluster): miscellaneous adjustments

- charts/base-cluster/templates/NOTES.txt
- charts/base-cluster/templates/flux/_create-authentication-key-secret-job.yaml
Remove the keyserver from the configuration as it will be disabled in the near future.
> feat(base-cluster): remove keyserver

- .github/scripts/validate-pullrequest.sh
- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/ci/basic-values.yaml
- charts/base-cluster/templates/NOTES.txt
- charts/base-cluster/templates/cert-manager/cert-manager.yaml
- charts/base-cluster/templates/cert-manager/clusterissuer.yaml
- charts/base-cluster/templates/dns/cloudflare/cert-manager.yaml
- charts/base-cluster/templates/dns/cloudflare/external-dns.yaml
- charts/base-cluster/templates/dns/external-dns.yaml
- charts/base-cluster/templates/global/certificates.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
> refactor(base-cluster)!: migrate `.dns.email` to `.certManager.email`,

- charts/base-cluster/Chart.lock
- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/values.schema.json
> feat(base-cluster)!: use flux as a direct helm dependency

- charts/base-cluster/values.yaml
> feat(base-cluster): lower base resource requests

- .github/scripts/create-values-diff.sh
- .github/scripts/extract-artifacthub-images.sh
- .github/scripts/templateGitHelmChart
- .github/scripts/templateHelmChart.sh
- .github/scripts/templateLocalHelmChart
- .github/scripts/templateRemoteHelmChart
- .github/workflows/pr-comment-diff.yaml
- .github/workflows/update-artifacthub-images.yaml
> feat(ci): post comment with diff on chart PRs

- .github/scripts/extract-artifacthub-images.sh
- .github/scripts/sync-codeowners.sh
- .github/scripts/validate-pullrequest.sh
This script sometimes fails and I don't know why 🤷
It works locally all the time
> feat(ci): cleanup TMP_DIR and add `-x` for better debugging

- .github/workflows/pr-comment-diff.yaml
See https://github.com/teutonet/teutonet-helm-charts/actions/runs/4022813708/jobs/6912948013
> fix(ci): Add CT_TARGET_BRANCH

- .github/scripts/extract-artifacthub-images.sh
add missing parameters
See https://github.com/teutonet/teutonet-helm-charts/actions/runs/4059862682/jobs/6995705499
> fix(ci): artifacthub image extration

- charts/base-cluster/templates/descheduler/descheduler.yaml
go templates handles ints very weirdly 😅
> fix(base-cluster): fix logic for selection latest version

- .github/workflows/semver.yaml
looks like it's working 👍️
https://github.com/cwrau/teutonet-helm-charts/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
> fix(ci): fix ci for new chart

- .github/workflows/release.yaml
See https://github.com/helm/chart-releaser-action/issues/100
> fix(ci): support releasing a single chart

- README.md
> feat(README): add links and description for the charts

- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/templates/cert-manager/clusterissuer.yaml
staging ClusterIssuer
Closes #183
> feat(base-cluster/ClusterIssuer): rename old ClusterIssuer and add

- .github/workflows/semver.yaml
This reverts commit 285c64f55cf94f282f9746e5749716981c08cffe.
> fix(ci): Revert "fix(ci): fix ci for new chart (#173)"

- .github/scripts/create-values-diff.sh
> feat(ci/diff): push to dpaste and insert link

- .github/CODEOWNERS
- charts/base-cluster/templates/_helmRelease.yaml
- charts/base-cluster/templates/_helpers.tpl
- charts/base-cluster/templates/cert-manager/cert-manager.yaml
- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/templates/dns/external-dns.yaml
- charts/base-cluster/templates/global/reflector.yaml
- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/kyverno/kyverno.yaml
- charts/base-cluster/templates/kyverno/policies/kyverno-base-policies/kyverno-policies.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/prometheus-operator.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/templates/monitoring/metrics-server/metrics-server.yaml
- charts/base-cluster/templates/monitoring/security/trivy.yaml
- charts/base-cluster/templates/nfs-server-provisioner/nfs-server-provisioner.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
> feat(base-cluster): move version so renovate can detect this

- .github/renovate.json
> feat(renovate): try detecting subcharts

- charts/t8s-cluster/templates/workload-cluster/_helmRelease.yaml
> fix(t8s-cluster/workload-cluster): change HelmRelease names to contain

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/templates/nfs-server-provisioner/nfs-server-provisioner.yaml
function, their docs are wrong tho 😅
> fix(base-cluster/storage): wrong usage of the "common.storage.class"

- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
> fix(t8s-cluster/clusterClass): only patch controlPlaneAvailabilityZones

- charts/base-cluster/values.schema.json
closes: https://github.com/teutonet/teutonet-helm-charts/issues/248
> feat(base-cluster): use current version dir for schema

- .github/scripts/create-values-diff.sh
add check for "edge"-case when there is no change
add option for dry-run
> fix(ci/diff): replace grep with yq for label deletion

- .github/scripts/create-values-diff.sh
- .github/scripts/templateHelmChart.sh
> feat(ci/diff): parallelize the diff

- .github/workflows/pr-comment-diff.yaml
Maybe double start glob works?
> fix(ci/diff): don't run on release-please branch

- charts/base-cluster/README.md.gotmpl
> feat(base-cluster/docs): add info about components

- .github/workflows/get-changed-charts.yaml
and fix typo for output variable
> fix(ci): add missing CT_TARGET_BRANCH env variable

- .github/scripts/templateHelmChart.sh
see https://github.com/teutonet/teutonet-helm-charts/actions/runs/4474409666/jobs/7862851650
> fix(ci/artifacthub-values): fix variable usage

- charts/base-cluster/templates/_helmRelease.yaml
- charts/base-cluster/templates/cert-manager/cert-manager.yaml
- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/templates/dns/external-dns.yaml
- charts/base-cluster/templates/global/reflector.yaml
- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/kyverno/kyverno.yaml
- charts/base-cluster/templates/kyverno/policies/kyverno-base-policies/kyverno-policies.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/prometheus-operator.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/templates/monitoring/metrics-server/metrics-server.yaml
- charts/base-cluster/templates/monitoring/security/trivy.yaml
- charts/base-cluster/templates/nfs-server-provisioner/nfs-server-provisioner.yaml
in preparation of https://github.com/fluxcd/helm-controller/issues/643 we raise the reconcile times, as the reconciliation might now really do some work, finally!
> feat(base-cluster): drift detection

- .github/cr.yaml
- .github/workflows/release-charts.yaml
feat(ci/release): don't set new release to latest
fix(ci/release): linting
Closes #284
> feat(ci/release): auto generate release notes with chart release

- charts/base-cluster/templates/flux/podMonitor.yaml
- charts/base-cluster/templates/flux/rules/flux-status.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
also update prometheusRule to alert on missing flux metrics
> feat(base-cluster/monitoring): add podMonitor and dashboard for flux

- .github/workflows/default-pullrequest.yaml
- .github/workflows/default-update-metadata.yaml
- .github/workflows/linter.yaml
this allows us to configure required checks for this see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
> feat(ci): add fallback checks and config for required checks

- .github/cr.yaml
- .github/workflows/release-charts.yaml
Somehow some changes got dropped
> fix(ci): weird stuff

- charts/stellio-context-broker/.helmignore
- charts/stellio-context-broker/Chart.lock
- charts/stellio-context-broker/Chart.yaml
- charts/stellio-context-broker/README.md.gotmpl
- charts/stellio-context-broker/templates/NOTES.txt
- charts/stellio-context-broker/templates/_helpers.tpl
- charts/stellio-context-broker/templates/api-gateway/deployment.yaml
- charts/stellio-context-broker/templates/api-gateway/service.yaml
- charts/stellio-context-broker/templates/ingress.yaml
- charts/stellio-context-broker/templates/kafka/configmap.yaml
- charts/stellio-context-broker/templates/kafka/deployment.yaml
- charts/stellio-context-broker/templates/kafka/persistentvolumeclaim.yaml
- charts/stellio-context-broker/templates/kafka/service.yaml
- charts/stellio-context-broker/templates/postgres/deployment.yaml
- charts/stellio-context-broker/templates/postgres/persistentvolumeclaim.yaml
- charts/stellio-context-broker/templates/postgres/secret.yaml
- charts/stellio-context-broker/templates/postgres/service.yaml
- charts/stellio-context-broker/templates/search/deployment.yaml
- charts/stellio-context-broker/templates/search/service.yaml
- charts/stellio-context-broker/templates/subscription/deployment.yaml
- charts/stellio-context-broker/templates/subscription/service.yaml
- charts/stellio-context-broker/values.yaml
We've internally created this chart for the stellio context broker
Now we're open-sourcing it! 🎉
> feat(stellio-context-broker): initial import of stellio-context-broker

- .github/scripts/prepare-values.sh
- .github/workflows/linter.yaml
- .github/workflows/pr-comment-diff.yaml
- .github/workflows/release-chart.yaml
- .github/workflows/update-artifacthub-images.yaml
> feat(ci): allow for values-generating scripts in CI

- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/values.yaml
Somehow some changes got dropped
> fix(base-cluster): weird stuff

- charts/base-cluster/templates/global/cluster-ingress.yaml
- charts/base-cluster/templates/ingress/nginx.yaml
> feat(base-cluster/ingress): set nginx as default ingerssClass

- charts/base-cluster/templates/_ingress.tpl
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_helpers.tpl
> fix(base-cluster/ingress): remove duplicate certs

- .github/workflows/actionlint.yaml
- .github/workflows/linter.yaml
- .github/workflows/release-update-metadata.yaml
- .github/workflows/validate-pullrequest.yaml
This should allow us to use the new RuleSets GitHub Feature 👍️
> feat(ci): use understandable names for jobs

- charts/t8s-cluster/templates/workload-cluster/pre-install/_uninstall-job.yaml
- charts/t8s-cluster/templates/workload-cluster/pre-install/uninstall-storageclasses.yaml
Also run the clusterResourceSet uninstall jobs on upgrades, in case something went under during the install
> fix(t8s-cluster/workload-cluster): add missing uninstall job for the storageclasses

- .github/workflows/update-artifacthub-images.yaml
- .github/workflows/update-codeowners.yaml
Otherwise the changed values files will also be committed 😅
> fix(ci): only commit specific files

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_alertmanager-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_grafana-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_kube-state-metrics-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus_config.yaml
chore(base-cluster/monitoring): formatting
> feat(base-cluster/monitoring): add trivy dashboard

- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/templates/global/prevent-uninstallation.yaml
> feat(base-cluster): add pre-delete hook and docs about uninstalling

- .github/renovate.json
> fix(ci/renovate): add oci registry support

- charts/t8s-cluster/templates/management-cluster/clusterClass/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_openStackClusterTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackMachineTemplates/_helpers.tpl
- charts/t8s-cluster/values.schema.json
managedSecurityGroups=true and only add additionalSecurityGroups instead of overwriting them
Closes #416
> fix(t8s-cluster/management-cluster): always set

- .github/scripts/prepare-values.sh
This allows the script to be run during a pre-commit hook
> feat(ci): allow skipping modifying the main values.yaml

- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
This adjusts the machineDeployments to roll more machines in parallel and to delete machines in a deterministic order by age
> feat(t8s-cluster/clusterClass): adjust machineDeployment rolling

- .github/scripts/enforce-trusted-registries.sh
- .github/scripts/trusted_images_regex.jq
- .github/trusted_registries.yaml
- .github/workflows/release-update-metadata.yaml
- .github/workflows/update-artifacthub-images.yaml
This is fulfilling https://gitlab.teuto.net/4teuto/ops/k8s/3rd-party-container-mgmt/-/issues/1 for our Helm Charts
> feat(ci): add script and config to enforce a list of trusted registries/images

- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_helpers.tpl
The parameter values have to be strings
> fix(t8s-cluster/clusterClass): fix parallel image pulling

- charts/base-cluster/templates/backup/velero.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
Closes https://github.com/teutonet/teutonet-helm-charts/issues/442
> fix(base-cluster/backup): reduce request, make configurable

- charts/t8s-cluster/templates/workload-cluster/cinder-csi-plugin.yaml
- charts/t8s-cluster/templates/workload-cluster/cloud-controller-manager.yaml
> feat(t8s-cluster/workload-cluster): adjust install order after CNI

- .github/scripts/templateHelmChart.sh
This should speed up CI quite a bit
> feat(ci): parallelize chart templating

- .github/scripts/create-values-diff.sh
see https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#delete-an-issue-comment
> fix(ci/diff): use correct REST API URL

- charts/base-cluster/templates/backup/velero.yaml
docker.io needs to be specified explicitly
> fix(base-cluster/velero): add docker.io as registry

- charts/base-cluster/templates/global/imagePullSecrets.yaml
> fix(base-cluster/imagePullSecrets): getting recreated upon reconciliation

- charts/t8s-cluster/templates/workload-cluster/pre-install/uninstall-storageclasses.yaml
Otherwise this will be run on a fresh cluster install
> fix(t8s-cluster/workload-cluster): cleanup of storageclasses

- .github/scripts/create-values-diff.sh
> feat(ci/diff): print new files instead of ignoring them

- .github/workflows/validate-and-label-pullrequest.yaml
I guess it's not installed by default anymore? 🤷
> fix(ci): install missing cocogitto

- charts/base-cluster/templates/monitoring/tracing/opentelemetry-collector.yaml
> fix(base-cluster/tracing): apparently tempo changed their service name

- charts/t8s-cluster/templates/workload-cluster/gpu-operator.yaml
don't know how this got through the cracks 😅
> fix(t8s-cluster/gpu-operator): fix worker affinity

- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/monitoring/tracing/opentelemetry-collector.yaml
chore(base-cluster/tracing): simplify tracing config even more
> feat(base-cluster/ingress): enable tracing for nginx

- charts/t8s-cluster/templates/management-cluster/cluster.yaml
who'd have thunked that names could be illegal label values 🤣 Not meeee
Closes #585
> fix(t8s-cluster/management-cluster): labels

- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
> feat(base-cluster/nginx): add toggle for snippets

- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_kubeadmControlPlaneTemplateSpec.yaml
this eases debugging in case of problems.
> feat(t8s-cluster/management-cluster): up the event ttl

- charts/t8s-cluster/ci/cidrs-values.yaml
- charts/t8s-cluster/ci/gpu-flavor-values.yaml
- charts/t8s-cluster/ci/injectedCertificateAuthorities-values.yaml
- charts/t8s-cluster/ci/securityGroups-values.yaml
- charts/t8s-cluster/templates/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/cluster.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/clusterClass.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/_kubeadmConfigTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/_nodePoolKubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/gpuNodePoolKubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/gpuWorkerKubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/standardNodePoolKubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmConfigTemplate/standardWorkerKubeadmConfigTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/_kubeadmControlPlaneTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/kubeadmnControlPlaneTemplate/kubeadmControlPlaneTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_openStackClusterTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/openStackClusterTemplate.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackMachineTemplates/_helpers.tpl
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackMachineTemplates/_openstackMachineTemplateSpec.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackMachineTemplates/openStackMachineTemplates.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/patches/_kubelet.tpl
- charts/t8s-cluster/templates/workload-cluster/etcd-defrag.yaml
- charts/t8s-cluster/templates/workload-cluster/gpu-operator.yaml
- charts/t8s-cluster/values.schema.json
- charts/t8s-cluster/values.yaml
Closes #584
Needs [gitlab.teuto.net/4teuto/ops/k8s/t8s-engine/-/merge_requests/661](https://gitlab.teuto.net/4teuto/ops/k8s/t8s-engine/-/merge_requests/661)
> feat(t8s-cluster/clusterClass)!: configure static machineDeploymentClasses instead of one per computePlane

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus_config.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
also add flag to only monitor rolled out namespaces
> feat(base-cluster/monitoring): monitor all namespaces by default

- charts/t8s-cluster/templates/workload-cluster/gpu-operator.yaml
> fix(t8s-cluster): allow greater than one gpu requests

- .github/renovate.json
must've missed that in the docs
> fix(renovate): wrap password in `encrypted` object

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/grafana-secret.yaml
these just have lots of the password as `@` instead of random stuff
> fix(base-cluster/monitoring): don't use bitnamis "strong" password

- charts/base-cluster/values.yaml
> fix(base-cluster/helmrepositories): add missing nginx condition

- .github/workflows/update-artifacthub-images.yaml
Needs https://github.com/teutonet/teutonet-helm-charts/pull/665
> feat(ci): auto-merge artifacthub-images

- .github/workflows/update-artifacthub-images.yaml
only prepare-values for the current chart
> feat(ci): improve image update workflow

- .github/cr.yaml
- .github/workflows/create-release-pr.yaml
- .github/workflows/release-chart.yaml
feat(ci): drop old helm repo
chore(ci): package using native helm
> feat(ci): create release via release-please

- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/ci/artifacthub-values.yaml
- charts/base-cluster/ci/deadmansswitch-values.yaml
- charts/base-cluster/ci/pagerduty-values.yaml
- charts/base-cluster/templates/_images.tpl
- charts/base-cluster/templates/monitoring/deadMansSwitch/ciliumNetworkPolicy.yaml
- charts/base-cluster/templates/monitoring/deadMansSwitch/cronjob.yaml
- charts/base-cluster/templates/monitoring/deadMansSwitch/hook-secret.yaml
- charts/base-cluster/templates/monitoring/deadMansSwitch/registration.yaml
- charts/base-cluster/templates/monitoring/deadMansSwitch/secret.yaml
- charts/base-cluster/templates/monitoring/deadMansSwitch/unregister.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_alertmanager-config.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/oauth-proxy.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
feat(base-cluster/monitoring): add deadMansSwitch integration
> feat(base-cluster/monitoring): add pagerduty alertmanager receiver

- .github/renovate.json
see https://developer.mend.io/github/teutonet/teutonet-helm-charts/-/job/018d0da3-42ee-7edd-bf8e-4253c8219562
> fix(renovate): try different url

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_grafana-config.yaml
Closes: https://github.com/teutonet/teutonet-helm-charts/issues/652
> feat(base-cluster/grafana): add dashboards for namespace monitoring

- .github/release-please/manifest.json
I finally could test this locally, this looks good to me
> fix(ci/release-please): set already released versions

- charts/teuto-portal-k8s-worker/ci/worker-values.yaml
- charts/teuto-portal-k8s-worker/values.schema.json
> feat(teuto-portal-k8s-worker)!: add environment parameter

- charts/base-cluster/templates/kyverno/kyverno.yaml
> fix(base-cluster/kyverno): configure missing registry for kyverno images

- charts/base-cluster/templates/_helmRelease.yaml
- charts/base-cluster/templates/backup/migrations/velero-4-to-5.yaml
- charts/base-cluster/templates/backup/velero.yaml
- charts/base-cluster/templates/cert-manager/cert-manager.yaml
- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/templates/dns/external-dns.yaml
- charts/base-cluster/templates/global/reflector.yaml
- charts/base-cluster/templates/ingress/nginx.yaml
- charts/base-cluster/templates/kyverno/kyverno.yaml
- charts/base-cluster/templates/kyverno/policies/kyverno-base-policies/kyverno-policies.yaml
- charts/base-cluster/templates/kyverno/validation.tpl
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/oauth-proxy.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/prometheus-operator.yaml
- charts/base-cluster/templates/monitoring/loki/loki.yaml
- charts/base-cluster/templates/monitoring/metrics-server/metrics-server.yaml
- charts/base-cluster/templates/monitoring/security/trivy.yaml
- charts/base-cluster/templates/monitoring/tracing/grafana-tempo.yaml
- charts/base-cluster/templates/monitoring/tracing/opentelemetry-collector.yaml
- charts/base-cluster/templates/nfs-server-provisioner/nfs-server-provisioner.yaml
> feat(base-cluster): upgrade all HRs and enable driftDetection

- charts/base-cluster/templates/monitoring/metrics-server/metrics-server.yaml
see https://github.com/bitnami/charts/commit/ed5f202f815
> chore(base-cluster/monitoring): remove unnecessary arg

- charts/base-cluster/README.md.gotmpl
docs(base-cluster): fix typos
Closes #823
> docs(base-cluster): add more info about ssh url

- .github/scripts/create-values-diff.sh
- .github/scripts/enforce-trusted-registries.sh
- .github/scripts/extract-artifacthub-images.sh
- .github/workflows/get-changed-chart.yaml
- .github/workflows/get-changed-charts.yaml
- .github/workflows/linter.yaml
- .github/workflows/pr-comment-diff.yaml
- .github/workflows/release-update-metadata.yaml
- .github/workflows/validate-pullrequest.yaml
- charts/common/Chart.lock
- charts/common/Chart.yaml
- charts/common/README.md.gotmpl
- charts/common/templates/_helm.tpl
- charts/common/templates/_resources.tpl
- charts/common/values.schema.json
adjust CI to work with library charts
> feat(common): initial implementation

- .github/workflows/create-release-prs.yaml
> feat(ci/release-please): set created release-please PRs to auto-merge

- charts/common/templates/_telemetry.tpl
> feat(common): add telemetry auto-detection template (#869)

- .github/workflows/create-release-prs.yaml
see https://github.com/teutonet/teutonet-helm-charts/actions/runs/8739717373/job/23981656380
> fix(ci): run inside git repo apparently needed

- .github/workflows/create-release-prs.yaml
- .github/workflows/release-chart.yaml
- .github/workflows/release-update-metadata.yaml
- README.md
- **fix(ci): https://github.com/teutonet/teutonet-helm-charts/actions/runs/9109565794/job/25042726458#step:4:1**
- **feat(ci): auto-generate sources for charts**
- **feat(ci): push images using GITHUB_TOKEN this should set the images to public by default, see https://stackoverflow.com/a/77094666**
- **chore(ci): remove deprecated repo, only OCI is supported**
> feat(ci): various adjustments

- .github/scripts/generate-sarif-reports.sh
- .github/workflows/scan-for-cves.yaml
> feat(ci): add cve scanning

- .github/workflows/scan-for-cves.yaml
See https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#homebrew-note
> fix(ci/cve-scanning): 🤦

- .github/scripts/generate-sarif-reports.sh
- .github/workflows/scan-for-cves.yaml
otherwise github can't take it 🙄
> fix(ci/cve-scanning): consolidate all runs into a single run

- charts/t8s-cluster/templates/workload-cluster/cloud-controller-manager.yaml
> fix(t8s-cluster/workload-cluster): this field is _actually_ used 🙄

- .github/workflows/wait-for-checks.yaml
This doesn't seem to work as expected, see https://github.com/teutonet/teutonet-helm-charts/actions/runs/10939362306/job/30369449677?pr=1181
> fix: Revert #1175

- .github/workflows/check-licenses.yaml
> chore(ci): only run license scan for the currently edited chart

- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_prometheus-stack-config.yaml
this eases the usage of these resources.
> feat(base-cluster/monitoring): create aggregate ClusterRoles

- charts/t8s-cluster/templates/workload-cluster/cni-cilium.yaml
this allows the customer to configure CiliumEgressGatewayPolicys
> feat(t8s-cluster/cilium): enable egressGateway

- .github/workflows/check-licenses.yaml
fix(ci): source linuxbrew env to make trivy available
> fix(ci): correctly run commands

- .github/scripts/generate-sarif-reports.sh
> fix(ci): now for real

- .github/scripts/scan-for-licenses.sh
This flag will scan more licenses then we need
> feat(ci): remove flag for full licencse scanning

- .github/scripts/scan-for-licenses.sh
also allow for spaces in license names
> fix(ci): add more licenses to whitelist

- .github/workflows/pr-comment-diff.yaml
Happened here: https://github.com/teutonet/teutonet-helm-charts/pull/1269/files#diff-1c060ea3361efbeee5f55dc7e6086ed9cdf182099274e382d630cac8a092dc60R28
> fix(ci/add-missing-token): token was deleted by accident(?)

- .github/workflows/pr-comment-diff.yaml
otherwise it just gets deleted 😅
> fix(ci): download after checkout

- .github/workflows/check-licenses.yaml
- .github/workflows/conventional-commits.yaml
- .github/workflows/label-pullrequest.yaml
- .github/workflows/pr-comment-diff.yaml
- .github/workflows/validate-pullrequest.yaml
- .github/workflows/wait-for-checks.yaml
also add concurrency to other jobs
> fix(ci): use correct concurrency key

- .github/workflows/release-chart.yaml
this is not included in the new 24.04 Ubuntu image
> fix(ci): install missing oras

- charts/t8s-cluster/templates/workload-cluster/cni-cilium.yaml
this results in unroutable/unrouted packets from/to hostnetwork pods
> fix(t8s-cluster/workload-cluster): turn off bpf.masquerade

- charts/common/templates/_telemetry.tpl
- charts/common/values.schema.json
add alloy as a receiving backend service
> feat(common/telemetry): abstract telemetry config to allow typed usage

- charts/base-cluster/templates/cert-manager/rules/certificate-expiration.yaml
- charts/base-cluster/templates/flux/rules/flux-status.yaml
- charts/base-cluster/templates/monitoring/kdave/rules/releases-with-deprecation.yaml
- quote templated fields
- remove unnecessary `-rules` suffix
- Add alerting for deprecated / removed APIs in helm releases
> feat(base-cluster/monitoring): improve alerting

- .github/renovate.json
see <https://docs.renovatebot.com/mend-hosted/migrating-secrets/>
> chore(renovate): migrate to new way of handling secrets

- charts/base-cluster/templates/flux/rules/flux-status.yaml
- charts/base-cluster/templates/monitoring/kube-prometheus-stack/_kube-state-metrics-config.yaml
see <https://github.com/fluxcd/flux2/issues/4652>
flux removed these metrics, without a breaking change!, so we have to
get them ourselves.
> fix(base-cluster/monitoring): migrate to new flux metrics

- .github/workflows/validate-pullrequest.yaml
> fix(ci): add missing env var

- .github/workflows/validate-pullrequest.yaml
> fix(ci): use gh api instead of git, there is no git repo

- charts/base-cluster/templates/descheduler/descheduler.yaml
- charts/base-cluster/values.schema.json
- charts/base-cluster/values.yaml
thanks descheduler for a breaking change in a minor version...
> chore(base-cluster/descheduler): migrate config

- charts/t8s-cluster/ci/securityGroupRules-values.yaml
- charts/t8s-cluster/templates/management-cluster/clusterClass/openStackClusterTemplate/_openStackClusterTemplateSpec.yaml
- charts/t8s-cluster/values.schema.json
this is one step further to also allow an included VPN service
> feat(t8s-cluster/management-cluster): add option to create SecurityGroupRules

- .github/workflows/check-licenses.yaml
- .github/workflows/scan-for-cves.yaml
Every time, why are basics not installed 😩
> fix(ci): install missing sponge
